options:
  merge-default-rules: true
  formatter: stylish
# File Options
files:
  include:
    - 'docroot/profiles/vicuni/themes/custom/**/*.scss'
    - 'docroot/profiles/vicuni/modules/custom/**/*.scss'
  ignore:
    - 'docroot/profiles/vicuni/themes/custom/**/build/.*'
    - 'docroot/profiles/vicuni/themes/custom/vu/sass/compass/**/*.scss'
    - 'docroot/profiles/vicuni/themes/custom/**/*.scss'
# Rule Configuration
rules:
  indentation:
    - 1
    -
      size: 2
  variable-name-format:
    - 1
    -
      allow-leading-underscore: true
  nesting-depth: 0
  placeholder-in-extend: 0
