<?php

/**
 * @file
 * Courses - How to Apply - Anchor link button block.
 */

/**
 * Class VuCoreHtaAnchorLinkButtonCourseBlock.
 */
class VuCoreHtaAnchorLinkButtonCourseBlock extends vuCoreCourseBlockBase {

  /**
   * {@inheritdoc}
   */
  public $condType = VU_CBS_TYPE_HE | VU_CBS_TYPE_VE;

  /**
   * {@inheritdoc}
   */
  public static $info = 'How to Apply - Anchor link button';

  /**
   * {@inheritdoc}
   */
  public $theme = 'vu_course_hta_anchor_link_button';

}
