<?php

/**
 * @file
 * Courses - How to Apply - Enquire button block.
 */

/**
 * Class VuCoreHtaEnquireButtonCourseBlock.
 */
class VuCoreHtaEnquireButtonCourseBlock extends vuCoreCourseBlockBase {

  /**
   * {@inheritdoc}
   */
  public $condAudience = VU_CBS_AUDIENCE_DOMESTIC;

  /**
   * {@inheritdoc}
   */
  public static $info = 'How to Apply - Enquire button';

  /**
   * {@inheritdoc}
   */
  public $theme = 'vu_course_hta_enquire_button';

}
